data = [
    {
        "id": 1,
        "name": "Neil Lopez",
        "phone": "(855) 541-8553",
        "email": "fermentum.risus@google.com",
        "region": "Risaralda",
        "country": "Germany",
    },
    {
        "id": 2,
        "name": "Rana Alvarez",
        "phone": "(162) 218-1884",
        "email": "orci.lacus@google.ca",
        "region": "Coahuila",
        "country": "Canada",
    },
    {
        "id": 3,
        "name": "Myra Cote",
        "phone": "1-241-222-3601",
        "email": "eu.tellus.phasellus@icloud.couk",
        "region": "South Jeolla",
        "country": "United States",
    },
    {
        "id": 4,
        "name": "Neville Glover",
        "phone": "1-356-763-1886",
        "email": "tellus.id.nunc@protonmail.net",
        "region": "Picardie",
        "country": "Indonesia",
    },
    {
        "id": 5,
        "name": "Cyrus Flores",
        "phone": "(696) 843-1586",
        "email": "sed.facilisis@hotmail.edu",
        "region": "Zhōngnán",
        "country": "Sweden",
    },
    {
        "id": 6,
        "name": "Sybill Blake",
        "phone": "(568) 141-4613",
        "email": "mi.pede@aol.edu",
        "region": "Loreto",
        "country": "Brazil",
    },
    {
        "id": 7,
        "name": "Noble Hurley",
        "phone": "(935) 754-6741",
        "email": "in.mi.pede@protonmail.net",
        "region": "Saskatchewan",
        "country": "Germany",
    },
    {
        "id": 8,
        "name": "Colette Dillard",
        "phone": "(837) 883-8556",
        "email": "amet.diam.eu@google.ca",
        "region": "Central Luzon",
        "country": "United States",
    },
    {
        "id": 9,
        "name": "Aidan Lane",
        "phone": "(235) 263-6714",
        "email": "commodo.tincidunt.nibh@aol.couk",
        "region": "Himachal Pradesh",
        "country": "Chile",
    },
    {
        "id": 10,
        "name": "Aurora Bright",
        "phone": "1-246-367-3934",
        "email": "est.ac@outlook.ca",
        "region": "Podkarpackie",
        "country": "Turkey",
    },
]